import { Observable } from 'rxjs/Observable';
import { OrderPipe } from 'ngx-order-pipe';
import { GridOption } from '../models/grid-option';

export abstract class ListElement {

  orderPipe: OrderPipe;
  items: any[];
  itemsFiltered: any[];
  configurations: any[];
  loading = false;
  errorMensage: string;
  idSelected: number;
  completeList = false;
  completeConfiguration = false;
  observer: any;
  itemChange: any;
  totalResults = 0;
  showFilter = false;
  textSearch = '';
  order = '';
  reverse = false;
  options: GridOption;

  constructor(
  ) {
    this.orderPipe = new OrderPipe();
    this.configureGridOption();
    this.items = [
      {
        "canDelete": false,
        "idSolicitud": "A1803",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "ABOGADO CORPORATIVO",
        "solicitante": "Eimmy Lizzette Rodriguez Macedo",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "LEGAL",
        "direccion": "ADMINISTRACION Y FINANZAS",
        "diasSolicitud": null,
        "active": true,
        "id": 1803
      },
      {
        "canDelete": false,
        "idSolicitud": "A1802",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "EJECUTIVO COMERCIAL CORPORATIVO",
        "solicitante": "Roberto Sánchez Vela",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Director de Área)",
        "tabulador": "$28,059.00 - $37,412.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1802
      },
      {
        "canDelete": false,
        "idSolicitud": "A1801",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "EJECUTIVO COMERCIAL CORPORATIVO",
        "solicitante": "Roberto Sánchez Vela",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": "$28,059.00 - $37,412.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1801
      },
      {
        "canDelete": false,
        "idSolicitud": "A1800",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "EJECUTIVO COMERCIAL CORPORATIVO",
        "solicitante": "Roberto Sánchez Vela",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Director de Área)",
        "tabulador": "$28,059.00 - $37,412.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1800
      },
      {
        "canDelete": false,
        "idSolicitud": "A1798",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO OPERATIVO NOC",
        "solicitante": "Jesús Alejandre Ulloa",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Dirección RH)",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1798
      },
      {
        "canDelete": false,
        "idSolicitud": "A1796",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "EJECUTIVO COMERCIAL CORPORATIVO SR",
        "solicitante": "Miriam Paola Alvarado Castillo",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": "Gabriela Guadalupe Murguía Mendez",
        "localidad": "Ciudad de México",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "1",
        "active": true,
        "id": 1796
      },
      {
        "canDelete": false,
        "idSolicitud": "A1795",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE PROYECTOS SR",
        "solicitante": "Oscar Martinez Torres",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Dirección RH)",
        "tabulador": null,
        "tipoPlaza": "Temporal",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1795
      },
      {
        "canDelete": false,
        "idSolicitud": "A1794",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "TÉCNICO DE REPORTES",
        "solicitante": "Miriam Verónica Camarillo Rojas",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Director de Área)",
        "tabulador": "$8,342.00 - $11,123.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1794
      },
      {
        "canDelete": false,
        "idSolicitud": "A1788",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Alfredo Rojas Acuña",
        "statusMatriz": "Rechazada",
        "statusRequisicion": "Rechazada",
        "tabulador": "$11,700.00 - $15,600.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1788
      },
      {
        "canDelete": false,
        "idSolicitud": "A1785",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "COORDINADOR DE IMPLEMENTACIÓN",
        "solicitante": "Roberto Dewar Castillo",
        "statusMatriz": "Entrevista por RH",
        "statusRequisicion": "Entrevista por RH",
        "tabulador": "$20,000.00 - $20,000.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Sebastiano Puglisi",
        "localidad": "Monterrey",
        "area": null,
        "direccion": null,
        "diasSolicitud": "25",
        "active": true,
        "id": 1785
      },
      {
        "canDelete": false,
        "idSolicitud": "A1784",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "COORDINADOR DE IMPLEMENTACIÓN",
        "solicitante": "Sergio Zepeda",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$21,654.00 - $21,654.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1784
      },
      {
        "canDelete": false,
        "idSolicitud": "A1783",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "ADMINISTRADOR DE PROYECTOS",
        "solicitante": "Héctor Manuel Díaz Velazco",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$21,654.00 - $21,654.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Gabriela Guadalupe Murguía Mendez",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "24",
        "active": true,
        "id": 1783
      },
      {
        "canDelete": false,
        "idSolicitud": "A1782",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "AUXILIAR ADMINISTRATIVO",
        "solicitante": "Daniel Isaac Daniel Isaac",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$21,000.00 - $21,000.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Monterrey",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1782
      },
      {
        "canDelete": false,
        "idSolicitud": "A1781",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Alejandro Rubio",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1781
      },
      {
        "canDelete": false,
        "idSolicitud": "A1780",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Ulises Soriano Castillo",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Ciudad de México",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1780
      },
      {
        "canDelete": false,
        "idSolicitud": "A1779",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Alejandro Gonzalez Garcia",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1779
      },
      {
        "canDelete": false,
        "idSolicitud": "A1778",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE IMPLEMENTACIÓN",
        "solicitante": "Sergio Zepeda",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Sebastiano Puglisi",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": "21",
        "active": true,
        "id": 1778
      },
      {
        "canDelete": false,
        "idSolicitud": "A1777",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE IMPLEMENTACIÓN",
        "solicitante": "Daniel Daniel",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1777
      },
      {
        "canDelete": false,
        "idSolicitud": "A1776",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL EMPRESARIAL",
        "solicitante": "Tania Zea Medina",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Cesar Alejandro Saldaña Sánchez",
        "localidad": "Otra localidad",
        "area": null,
        "direccion": null,
        "diasSolicitud": "24",
        "active": true,
        "id": 1776
      },
      {
        "canDelete": false,
        "idSolicitud": "A1775",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL EMPRESARIAL",
        "solicitante": "Tania Zea Medina",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Cesar Alejandro Saldaña Sánchez",
        "localidad": "Otra localidad",
        "area": null,
        "direccion": null,
        "diasSolicitud": "24",
        "active": true,
        "id": 1775
      },
      {
        "canDelete": false,
        "idSolicitud": "A1774",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL EMPRESARIAL",
        "solicitante": "David Oviedo Lopez",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1774
      },
      {
        "canDelete": false,
        "idSolicitud": "A1773",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL EMPRESARIAL",
        "solicitante": "Tania Zea Medina",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Cesar Alejandro Saldaña Sánchez",
        "localidad": "Otra localidad",
        "area": null,
        "direccion": null,
        "diasSolicitud": "24",
        "active": true,
        "id": 1773
      },
      {
        "canDelete": false,
        "idSolicitud": "A1772",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL EMPRESARIAL",
        "solicitante": "Tania Zea Medina",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Cesar Alejandro Saldaña Sánchez",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": "24",
        "active": true,
        "id": 1772
      },
      {
        "canDelete": false,
        "idSolicitud": "A1771",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "ARQUITECTO DE SOLUCIONES",
        "solicitante": "Sergio Zepeda",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$17,461.00 - $17,461.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1771
      },
      {
        "canDelete": false,
        "idSolicitud": "A1770",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "ADMINISTRACIÓN COMERCIAL",
        "solicitante": "Erika Flores",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$14,087.00 - $14,087.00",
        "tipoPlaza": "Temporal",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1770
      },
      {
        "canDelete": false,
        "idSolicitud": "A1769",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL EMPRESARIAL",
        "solicitante": "Tania Zea Medina",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$14,087.00 - $14,087.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Cesar Alejandro Saldaña Sánchez",
        "localidad": "Otra localidad",
        "area": null,
        "direccion": null,
        "diasSolicitud": "24",
        "active": true,
        "id": 1769
      },
      {
        "canDelete": false,
        "idSolicitud": "A1768",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "RECLUTAMIENTO Y SELECCIÓN",
        "solicitante": "Ana Laura Ciprián Chagolla",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$11,357.00 - $11,357.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Monterrey",
        "area": "RH",
        "direccion": "DIRECCIÓN GENERAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1768
      },
      {
        "canDelete": false,
        "idSolicitud": "A1767",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE IMPLEMENTACIÓN",
        "solicitante": "Hugo Alejandro Renova Aguilar",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$9,659.00 - $9,659.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Monterrey",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1767
      },
      {
        "canDelete": false,
        "idSolicitud": "A1766",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE IMPLEMENTACIÓN",
        "solicitante": "Hugo Alejandro Renova Aguilar",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$9,659.00 - $9,659.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Monterrey",
        "area": null,
        "direccion": null,
        "diasSolicitud": null,
        "active": true,
        "id": 1766
      },
      {
        "canDelete": false,
        "idSolicitud": "A1765",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "DIRECTOR DE OPERACIONES",
        "solicitante": "Anhery Leyva Madrigal",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": "$55,856.00 - $55,856.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Guadalajara",
        "area": "RH",
        "direccion": "DIRECCIÓN GENERAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1765
      },
      {
        "canDelete": false,
        "idSolicitud": "A1764",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "COORDINADOR DE SOPORTE Y OPERACIÓN",
        "solicitante": "Sergio Zepeda",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$46,541.00 - $46,541.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Sebastiano Puglisi",
        "localidad": "Guadalajara",
        "area": null,
        "direccion": null,
        "diasSolicitud": "24",
        "active": true,
        "id": 1764
      },
      {
        "canDelete": false,
        "idSolicitud": "A1762",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "ADMINISTRADOR DE PROYECTOS",
        "solicitante": "Francisco Zermeño Vázquez",
        "statusMatriz": "Pendiente por reasignar",
        "statusRequisicion": "Pendiente por reasignar",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": "Ana Laura Ciprián Chagolla",
        "localidad": "Monterrey",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1762
      },
      {
        "canDelete": false,
        "idSolicitud": "A1760",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "EJECUTIVO COMERCIAL CORPORATIVO SR",
        "solicitante": "Ricardo Garcia Ponce",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Director de Área)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Otra localidad",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1760
      },
      {
        "canDelete": false,
        "idSolicitud": "A1758",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "SUPERVISOR DE GESTORES DE MEDICIÓN",
        "solicitante": "Jose Alberto De la Torre Medina",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": "Sebastiano Puglisi",
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "21",
        "active": true,
        "id": 1758
      },
      {
        "canDelete": false,
        "idSolicitud": "A1755",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "INGENIERO DE PROYECTOS JR",
        "solicitante": "Oscar Martinez Torres",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1755
      },
      {
        "canDelete": false,
        "idSolicitud": "A1754",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "INGENIERO DE PROYECTOS JR",
        "solicitante": "Raul Maldonado Sanchez",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Guadalajara",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1754
      },
      {
        "canDelete": false,
        "idSolicitud": "A1752",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Gisela Muciño Padilla",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$19,486.00 - $25,982.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Gabriela Guadalupe Murguía Mendez",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "18",
        "active": true,
        "id": 1752
      },
      {
        "canDelete": false,
        "idSolicitud": "A1751",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "COORDINADOR DE PREVENTA",
        "solicitante": "José Roberto Niño González",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1751
      },
      {
        "canDelete": false,
        "idSolicitud": "A1750",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "CONSULTOR PREVENTA",
        "solicitante": "José Roberto Niño González",
        "statusMatriz": "Rechazada",
        "statusRequisicion": "Rechazada",
        "tabulador": "$33,670.00 - $44,894.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1750
      },
      {
        "canDelete": false,
        "idSolicitud": "A1748",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "TÉCNICO DE REPORTES",
        "solicitante": "Olinser Castro Amezcua",
        "statusMatriz": "Rechazada",
        "statusRequisicion": "Rechazada",
        "tabulador": "$8,342.00 - $11,123.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1748
      },
      {
        "canDelete": false,
        "idSolicitud": "A1746",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "ASIGNACIÓN DE SERVICIOS",
        "solicitante": "Olinser Castro Amezcua",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": "$6,674.00 - $8,899.00",
        "tipoPlaza": "Temporal",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1746
      },
      {
        "canDelete": false,
        "idSolicitud": "A1745",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "ESPECIALISTA EN COMPRAS",
        "solicitante": "Raúl Sánchez Navarro",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Guadalajara",
        "area": "COMPRAS Y LOGÍSTICA",
        "direccion": "ADMINISTRACION Y FINANZAS",
        "diasSolicitud": null,
        "active": true,
        "id": 1745
      },
      {
        "canDelete": false,
        "idSolicitud": "A1743",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "TÉCNICO DE REPORTES",
        "solicitante": "Alfredo Rojas Acuña",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Director de Área)",
        "tabulador": "$8,342.00 - $11,123.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1743
      },
      {
        "canDelete": false,
        "idSolicitud": "A1740",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "ADMINISTRADOR DE PROYECTOS",
        "solicitante": "Francisco Zermeño Vázquez",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": "$13,033.00 - $17,378.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1740
      },
      {
        "canDelete": false,
        "idSolicitud": "A1739",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "INGENIERO DE PROYECTOS JR",
        "solicitante": "Raul Maldonado Sanchez",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Guadalajara",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1739
      },
      {
        "canDelete": false,
        "idSolicitud": "A1735",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "EJECUTIVO COMERCIAL EMPRESARIAL",
        "solicitante": "Sergio Antonio Pérez Garcia",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$16,290.00 - $21,720.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Mayra Lee Hernandez",
        "localidad": "Guadalajara",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "80",
        "active": true,
        "id": 1735
      },
      {
        "canDelete": false,
        "idSolicitud": "A1729",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "ASESOR DE CUENTAS POR PAGAR",
        "solicitante": "Maria Guadalupe Macias Hernandez",
        "statusMatriz": "Entrevista por RH",
        "statusRequisicion": "Entrevista por RH",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": "Mayra Lee Hernandez",
        "localidad": "Guadalajara",
        "area": "FINANZAS",
        "direccion": "ADMINISTRACION Y FINANZAS",
        "diasSolicitud": "84",
        "active": true,
        "id": 1729
      },
      {
        "canDelete": false,
        "idSolicitud": "A1728",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "COORDINADOR DE SELECCIÓN DE PROVEEDORES",
        "solicitante": "Enrique Manuel Fernández Ruíz",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": "$28,059.00 - $37,412.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Guadalajara",
        "area": "COMPRAS Y LOGÍSTICA",
        "direccion": "ADMINISTRACION Y FINANZAS",
        "diasSolicitud": null,
        "active": true,
        "id": 1728
      },
      {
        "canDelete": false,
        "idSolicitud": "A1727",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "CONSULTOR PREVENTA",
        "solicitante": "Sergio Antonio Pérez Garcia",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$33,670.00 - $44,894.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Cesar Alejandro Saldaña Sánchez",
        "localidad": "Guadalajara",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "77",
        "active": true,
        "id": 1727
      },
      {
        "canDelete": false,
        "idSolicitud": "A1726",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "ASIGNACIÓN DE SERVICIOS",
        "solicitante": "Miriam Verónica Camarillo Rojas",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$6,674.00 - $8,899.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": "Gabriela Guadalupe Murguía Mendez",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "3",
        "active": true,
        "id": 1726
      },
      {
        "canDelete": false,
        "idSolicitud": "A1720",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "INGENIERO OPERATIVO NOC",
        "solicitante": "Jesús Alejandre Ulloa",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": "Sebastiano Puglisi",
        "localidad": "Guadalajara",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "89",
        "active": true,
        "id": 1720
      },
      {
        "canDelete": false,
        "idSolicitud": "A1717",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "TÉCNICO DE REPORTES",
        "solicitante": "Alfredo Rojas Acuña",
        "statusMatriz": "Rechazada",
        "statusRequisicion": "Rechazada",
        "tabulador": "$8,342.00 - $11,123.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1717
      },
      {
        "canDelete": false,
        "idSolicitud": "A1716",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "CONSULTOR FUNCIONAL",
        "solicitante": "Francisco Javier Santana Aguayo",
        "statusMatriz": "Entrevista por RH",
        "statusRequisicion": "Entrevista por RH",
        "tabulador": "$23,383.00 - $31,178.00",
        "tipoPlaza": "Permanente",
        "reclutador": "Mayra Lee Hernandez",
        "localidad": "Guadalajara",
        "area": "TEC",
        "direccion": "TEC, APLICACIONES Y TI",
        "diasSolicitud": "79",
        "active": true,
        "id": 1716
      },
      {
        "canDelete": false,
        "idSolicitud": "A1715",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "TÉCNICO DE REPORTES",
        "solicitante": "Alfredo Rojas Acuña",
        "statusMatriz": "Rechazada",
        "statusRequisicion": "Rechazada",
        "tabulador": "$8,342.00 - $11,123.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": null,
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1715
      },
      {
        "canDelete": false,
        "idSolicitud": "A1712",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE DESARROLLO",
        "solicitante": "Francisco Javier Santana Aguayo",
        "statusMatriz": "Entrevista Pendiente",
        "statusRequisicion": "Entrevista Pendiente",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": "Mayra Lee Hernandez",
        "localidad": "Guadalajara",
        "area": "TEC",
        "direccion": "TEC, APLICACIONES Y TI",
        "diasSolicitud": "70",
        "active": true,
        "id": 1712
      },
      {
        "canDelete": false,
        "idSolicitud": "A1711",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "CONSULTOR FUNCIONAL",
        "solicitante": "Francisco Javier Santana Aguayo",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": "Mayra Lee Hernandez",
        "localidad": "Guadalajara",
        "area": "TEC",
        "direccion": "TEC, APLICACIONES Y TI",
        "diasSolicitud": "15",
        "active": true,
        "id": 1711
      },
      {
        "canDelete": false,
        "idSolicitud": "A1710",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE DESARROLLO",
        "solicitante": "Francisco Javier Santana Aguayo",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": null,
        "localidad": "Guadalajara",
        "area": "TEC",
        "direccion": "TEC, APLICACIONES Y TI",
        "diasSolicitud": null,
        "active": true,
        "id": 1710
      },
      {
        "canDelete": false,
        "idSolicitud": "A1709",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE PROCESOS",
        "solicitante": "Jose Alberto Rivera de la Torre",
        "statusMatriz": "Decisión",
        "statusRequisicion": "Decisión",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": "Mayra Lee Hernandez",
        "localidad": "Guadalajara",
        "area": "TEC",
        "direccion": "TEC, APLICACIONES Y TI",
        "diasSolicitud": "79",
        "active": true,
        "id": 1709
      },
      {
        "canDelete": false,
        "idSolicitud": "A1708",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE CALIDAD DE PRUEBAS",
        "solicitante": "Francisco Javier Santana Aguayo",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$16,290.00 - $21,720.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": "Mayra Lee Hernandez",
        "localidad": "Guadalajara",
        "area": "TEC",
        "direccion": "TEC, APLICACIONES Y TI",
        "diasSolicitud": "15",
        "active": true,
        "id": 1708
      },
      {
        "canDelete": false,
        "idSolicitud": "A1707",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "SUPERVISOR DE GESTORES DE MEDICIÓN",
        "solicitante": "Jose Alberto De la Torre Medina",
        "statusMatriz": "Entrevista por RH",
        "statusRequisicion": "Entrevista por RH",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": "Javier Mauricio Cordero Cerecero",
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "91",
        "active": true,
        "id": 1707
      },
      {
        "canDelete": false,
        "idSolicitud": "A1706",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "SUPERVISOR DE GESTORES DE MEDICIÓN",
        "solicitante": "Jose Alberto De la Torre Medina",
        "statusMatriz": "Entrevista por RH",
        "statusRequisicion": "Entrevista por RH",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": "Sebastiano Puglisi",
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "91",
        "active": true,
        "id": 1706
      },
      {
        "canDelete": false,
        "idSolicitud": "A1705",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "SUPERVISOR DE GESTORES DE MEDICIÓN",
        "solicitante": "Jose Alberto De la Torre Medina",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": "Javier Mauricio Cordero Cerecero",
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "91",
        "active": true,
        "id": 1705
      },
      {
        "canDelete": false,
        "idSolicitud": "A1701",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL PYME",
        "solicitante": "Ricardo Garcia Ponce",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": "Saúl Soto Sánchez",
        "localidad": "Otra localidad",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "77",
        "active": true,
        "id": 1701
      },
      {
        "canDelete": false,
        "idSolicitud": "A1700",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL PYME",
        "solicitante": "Ricardo Garcia Ponce",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": "Saúl Soto Sánchez",
        "localidad": "Otra localidad",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": "77",
        "active": true,
        "id": 1700
      },
      {
        "canDelete": false,
        "idSolicitud": "A1698",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "EJECUTIVO COMERCIAL PYME",
        "solicitante": "Ricardo Garcia Ponce",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Director de Área)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Otra localidad",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1698
      },
      {
        "canDelete": false,
        "idSolicitud": "A1697",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Gisela Muciño Padilla",
        "statusMatriz": "Entrevista por RH",
        "statusRequisicion": "Entrevista por RH",
        "tabulador": "$19,486.00 - $25,982.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": "Saúl Soto Sánchez",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "97",
        "active": true,
        "id": 1697
      },
      {
        "canDelete": false,
        "idSolicitud": "A1696",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Gisela Muciño Padilla",
        "statusMatriz": "Entrevista por RH",
        "statusRequisicion": "Entrevista por RH",
        "tabulador": "$19,486.00 - $25,982.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": "Saúl Soto Sánchez",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "97",
        "active": true,
        "id": 1696
      },
      {
        "canDelete": false,
        "idSolicitud": "A1695",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Gisela Muciño Padilla",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$19,486.00 - $25,982.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": "Saúl Soto Sánchez",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "97",
        "active": true,
        "id": 1695
      },
      {
        "canDelete": false,
        "idSolicitud": "A1694",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Gisela Muciño Padilla",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$19,486.00 - $25,982.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": "Saúl Soto Sánchez",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "97",
        "active": true,
        "id": 1694
      },
      {
        "canDelete": false,
        "idSolicitud": "A1693",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "GERENTE COMERCIAL",
        "solicitante": "Mario Alberto Jimenez",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": "$33,670.00 - $44,894.00",
        "tipoPlaza": "Temporal",
        "reclutador": null,
        "localidad": "Guadalajara",
        "area": "DESARROLLO DE NEGOCIO",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1693
      },
      {
        "canDelete": false,
        "idSolicitud": "A1692",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "COORDINADOR DE SOPORTE Y OPERACIÓN",
        "solicitante": "Juan Carlos Dávila Ortiz",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": "$28,059.00 - $37,412.00",
        "tipoPlaza": "Por proyecto",
        "reclutador": "Saúl Soto Sánchez",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "72",
        "active": true,
        "id": 1692
      },
      {
        "canDelete": false,
        "idSolicitud": "A1688",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "INGENIERO DE PROYECTOS JR",
        "solicitante": "Oscar Martinez Torres",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Coordinador de Reclutamiento y Selección)",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Cancún",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1688
      },
      {
        "canDelete": false,
        "idSolicitud": "A1687",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "INGENIERO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Héctor Quiñones Talamantes",
        "statusMatriz": "Rechazada",
        "statusRequisicion": "Rechazada",
        "tabulador": "$11,700.00 - $15,600.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Guadalajara",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1687
      },
      {
        "canDelete": false,
        "idSolicitud": "A1686",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "TÉCNICO DE SOPORTE Y OPERACIÓN",
        "solicitante": "Héctor Quiñones Talamantes",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorización (Presupuesto)",
        "tabulador": "$10,427.00 - $13,903.00",
        "tipoPlaza": "Permanente",
        "reclutador": null,
        "localidad": "Guadalajara",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": null,
        "active": true,
        "id": 1686
      },
      {
        "canDelete": false,
        "idSolicitud": "A1684",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "SUPERVISOR DE GESTORES DE MEDICIÓN",
        "solicitante": "Jose Alberto De la Torre Medina",
        "statusMatriz": "Rechazada",
        "statusRequisicion": "Rechazada",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": null,
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1684
      },
      {
        "canDelete": false,
        "idSolicitud": "A1683",
        "motivoIngreso": "Plaza nueva",
        "puestoSolicitado": "SUPERVISOR DE GESTORES DE MEDICIÓN",
        "solicitante": "Jose Alberto De la Torre Medina",
        "statusMatriz": "Pendiente de autorizar",
        "statusRequisicion": "Pendiente de autorizar",
        "tabulador": null,
        "tipoPlaza": "Por proyecto",
        "reclutador": null,
        "localidad": "Monterrey",
        "area": "COMERCIAL",
        "direccion": "COMERCIAL",
        "diasSolicitud": null,
        "active": true,
        "id": 1683
      },
      {
        "canDelete": false,
        "idSolicitud": "A1682",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "INGENIERO DE SERVICIO Y SOPORTE N2 SR",
        "solicitante": "Gisela Muciño Padilla",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": "Javier Mauricio Cordero Cerecero",
        "localidad": "Monterrey",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "80",
        "active": true,
        "id": 1682
      },
      {
        "canDelete": false,
        "idSolicitud": "A1681",
        "motivoIngreso": "Sustitución",
        "puestoSolicitado": "INGENIERO DE SERVICIO Y SOPORTE N2 SR",
        "solicitante": "Gisela Muciño Padilla",
        "statusMatriz": "Busqueda de candidatos",
        "statusRequisicion": "Busqueda de candidatos",
        "tabulador": null,
        "tipoPlaza": "Permanente",
        "reclutador": "Sebastiano Puglisi",
        "localidad": "Ciudad de México",
        "area": "INGENIERÍA",
        "direccion": "INGENIERÍA",
        "diasSolicitud": "77",
        "active": true,
        "id": 1681
      }]
    
  }

  abstract configureGridOption();

  init() {
    this.initAction();
    this.getDatasInit().subscribe(
      next => {},
      error => this.handlerError(error),
      () => this.completeAction()
    );
  }

  initAction() {
    this.loading = true;
  }

  getDatasInit() {
    const request = new Observable((observer) => {
      this.observer = observer;
      this.getListService();
    });
    return request;
  }

  abstract getListService();

  handlerError(error: string) {
    this.errorMensage = error;
    this.alertService();
    this.completeAction();
  }

  abstract alertService();

  completeAction() {
    this.loading = false;
  }

  abstract get ruta();

  toggleFilter(toggle: boolean) {
    this.showFilter = toggle;
  }

  textFilter(textSearch: string) {

    this.textSearch = textSearch;

    if (this.textSearch === '') {
      this.itemsFiltered = [];
    } else {
      this.itemsFiltered = this.getItemsFiltered();
    }

    this.totalResults = this.itemsFiltered.length;
  }

  getItemsFiltered() {
    const columnsTextSearch = this.getColumnsTextSearch();
    return this.items.filter(
      f => columnsTextSearch.findIndex( fi =>
        f[fi.field] && f[fi.field].toString().toUpperCase().indexOf(this.textSearch.toUpperCase()) !== -1
      ) >= 0
    );
  }

  getColumnsTextSearch() {
    return this.options.columnsDefs.filter( f => f.isVisible);
  }

  onShowFilter() {
    this.toggleFilter(true);
  }

  orderByChange(event: any) {
    this.order = event.column;
    this.reverse = event.reverse;
    this.itemsFiltered = this.orderPipe.transform(this.itemsFiltered, this.order, this.reverse, true);
  }

  columnsFilterForm(event: any) {
    this.columnsFilterFormCustom();
    if (event.controls && event.keys) {
      this.itemsFiltered = this.items.filter(item => {
        const notMatchingField = event.keys.every( key =>
          event.controls[key].value.findIndex( value => value === item[key]) >= 0
        );
        return notMatchingField;
      });
      this.totalResults = this.itemsFiltered.length;
    }
  }

  abstract columnsFilterFormCustom();

  next(next: any[]) {
    if (!next || next == null) {
      return;
    }

    this.items = next;
    this.itemsFiltered = next;
    if (next) {
      this.totalResults = next.length;
    }
  }

  abstract btnAction(event: any);

}
